name: human_place_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  youtube_api: ^1.0.4 
  photo_view: ^0.15.0
  http: ^0.13.5 # No actualizado por flutter_automation
  url_launcher: ^6.2.3 
  cached_network_image: ^3.3.1 
  uuid: ^4.3.3 
  flutter_easyloading: ^3.0.5 
  provider: ^6.1.1 
  shared_preferences: ^2.2.2 
  bubble: ^1.2.1
  just_audio: ^0.9.36 
  http_parser: ^4.0.2
  rxdart: ^0.27.7 
  sign_in_with_apple: ^6.1.4 
  crypto: ^3.0.3 
  video_player: ^2.8.2 
  rive: ^0.13.20 
  flip_card: ^0.7.0
  flutter_keyboard_visibility: ^6.0.0 
  youtube_player_flutter: ^9.1.1 
  metadata_fetch: ^0.4.1
  youtube_metadata: ^1.0.1
  audio_video_progress_bar: ^2.0.1
  basic_utils: ^5.5.4	 # Solo se logro actualizar hasta 5.5.4 por otras dependencias
  material_design_icons_flutter: ^7.0.7296
  # firebase
  firebase_core: ^3.8.1 
  firebase_auth: ^5.3.4 
  firebase_analytics: ^11.3.6
  cloud_functions: ^5.2.0
  google_sign_in: ^6.2.1 
  cloud_firestore: ^5.5.1 
  firebase_messaging: ^15.1.6 
  flutter_automation: ^2.0.0
  card_slider: ^1.0.5
  gallery_image_viewer: ^1.2.0
  flutter_carousel_widget: ^3.1.0

dependencies_overrides:
  archive: ^3.6.1
  win32: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.2

flutter:
  fonts:
    - family: sen-regular
      fonts:
        - asset: assets/fonts/sen/sen-regular.otf

    - family: sen-bold
      fonts:
        - asset: assets/fonts/sen/sen-bold.otf

    - family: roboto-regular
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logos/
    - assets/images/
    - assets/images/badge-ovejero/
    - assets/images/personajes/
    - assets/images/planta/
    - assets/animationsRive/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/icons/icon.png"
  image_path_ios: "assets/icons/icon_ios.png"

